spring.application.name=GESTION DES INTERVENTIONS 
spring.datasource.url=jdbc:mysql://localhost:3306/gestionDesInterventions?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api

##link swager : http://localhost:8080/api/swagger-ui/index.html


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khalilbaidouri2020@gmail.com
spring.mail.password=lwua zbfc uxwd uszp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000 

server.port=8080

logging.level.org.springframework.security=DEBUG

