###
//INSCRIPTION
POST http://localhost:8080/api/inscription
Content-Type: application/json

{
  "nom" : "khalil",
  "prenom" : "baidouri",
  "email" : "khalilbaidouri97@gmail.com",
  "matrecule" : "bb226814",
  "password" : "Qwerty@123"
}
###
// Activation
POST http://localhost:8080/api/activation
Content-Type: application/json

{
  "code" : "367508 "
}
###

###
// CONNEXION
###
POST http://localhost:8080/api/connexion
Content-Type: application/json

{
  "email" : "admin@gmail.com",
  "password" : "admin"
}
###

###
// DEPOSER UNE AVIS
POST http://localhost:8080/api/avis
Content-Type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6IiQyYSQxMCROSHQ2cFZzUG9WSzV5cFk2ME5xWmNlYVQvTEZjWDI5MlNWMFZPOHhqVVJKMDB2b1JTa05jLiIsImV4cCI6MTc1MjI5MDg1NSwidXNlcm5hbWUiOiJtYW5hZ2VyQGdtYWlsLmNvbSIsInN1YiI6Im1hbmFnZXJAZ21haWwuY29tIn0.jGRSxMt6f_ctVQKWcTZwi9dq9rUlS10kZYgWdZHGHi4

{
   "message" : "khalil 5 "
}
###

###
// AFFICHER MES INFORMATIONS
GET http://localhost:8080/api/mesInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6IiQyYSQxMCQ2OHhLNnJZNGRBQlBSZUtvUklDVkFlanI3NVFoQnI0VGxaemM0WFdYSUFIb2NYeWpPQVB2UyIsImV4cCI6MTc1MzgxNjcxOCwidXNlcm5hbWUiOiJtYW5hZ2VyQGdtYWlsLmNvbSIsInN1YiI6Im1hbmFnZXJAZ21haWwuY29tIn0.xbP52aEq_HCLQqIK7YIBwsfkrTYmbraQkMZfFytF2V0

{

}
###

###
// REFRESH TOKEN
POST http://localhost:8080/api/refreshToken
Content-Type: application/json

{
  "token" : "f4b7d983-aea6-4b32-a3c3-cf86c35aebca"
}
###
###
// ALTER PASSWORD

POST http://localhost:8080/api/alterPassword
Content-Type: application/json

{
  "username": "khalilbaidouri97@gmail.com"
}
###

###
// NEW PASSWORD

POST http://localhost:8080/api/alterPassword
Content-Type: application/json

{
    "username" : "khalilbaidouri97@gmail.com",
    "code" : "367508",
    "password" :"Qwerty@123"
}

###



###
//AVIS
GET http://localhost:8080/api/avis
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImV4cCI6MTc1MjI2MzAxNywicGFzc3dvcmQiOiIkMmEkMTAkMDF6STdyUTRQV3pQOHJzLzA1cmVQTzV0LzlSRVpHM0ltVG1oOXBpcGdBZ2tUMVBLd1hvMnEifQ.Ufo1m5ICuNL6oVSMAkXkmJx31ypReoSx06V1-LPauEY
###
//DEMANDE INTERVENTION
POST http://localhost:8080/api/demande
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im1hbmFnZXJAZ21haWwuY29tIiwiZXhwIjoxNzUzODE2MDEyLCJwYXNzd29yZCI6IiQyYSQxMCQ2OHhLNnJZNGRBQlBSZUtvUklDVkFlanI3NVFoQnI0VGxaemM0WFdYSUFIb2NYeWpPQVB2UyIsInN1YiI6Im1hbmFnZXJAZ21haWwuY29tIn0.zdX1XloQyBiO_21uxJO7yhUYg8CogIajfEBzb44idN4

{
  "nom": "hihi",
  "priorite": "BASSE",
  "description": "wicjhbw",
  "localisation": "w7d lblasa"
}

###
//MODIFIER DEMANDE   //21042007
POST http://localhost:8080/api/29/modifier
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im1hbmFnZXJAZ21haWwuY29tIiwiZXhwIjoxNzUzODE2MDEyLCJwYXNzd29yZCI6IiQyYSQxMCQ2OHhLNnJZNGRBQlBSZUtvUklDVkFlanI3NVFoQnI0VGxaemM0WFdYSUFIb2NYeWpPQVB2UyIsInN1YiI6Im1hbmFnZXJAZ21haWwuY29tIn0.zdX1XloQyBiO_21uxJO7yhUYg8CogIajfEBzb44idN4

{
  "nom": "hhhh",
  "priorite": "BASSE",
  "description": "hhhh",
  "localisation": "hhhh",
  "typeIntervention": "hhhhh"
}

###
//GET INTERVENTION PAR PRIORITE

GET http://localhost:8080/api/interventions/afficherLesInterventionsParPriotite?priorite=HAUTE
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6IiQyYSQxMCRxa0Nab211NzB4WmRieVBXU0Y3a1dlOENmS0xPZHN1TGo0b0JCRWFzQ0RpblJPS2xxejQ0cSIsImV4cCI6MTc1MzQ0NTg2OCwidXNlcm5hbWUiOiJhZG1pbkBnbWFpbC5jb20iLCJzdWIiOiJhZG1pbkBnbWFpbC5jb20ifQ.4xqP3d1nJrUGBwqFkc7-7M-gBRv_TniXTCtfOMEUFkA

{

}

###
//GET DEMANDE PAR ETAT

GET http://localhost:8080/api/afficherLesInterventionsParEtat?priorite=HAUTE
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im1hbmFnZXJAZ21haWwuY29tIiwiZXhwIjoxNzUzODE2MDEyLCJwYXNzd29yZCI6IiQyYSQxMCQ2OHhLNnJZNGRBQlBSZUtvUklDVkFlanI3NVFoQnI0VGxaemM0WFdYSUFIb2NYeWpPQVB2UyIsInN1YiI6Im1hbmFnZXJAZ21haWwuY29tIn0.zdX1XloQyBiO_21uxJO7yhUYg8CogIajfEBzb44idN4

{}


###
//GET INTERVENTION PAR STATUT

GET http://localhost:8080/api/interventions/afficherLesInterventionsParStatut?statut=EN_COURS
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImV4cCI6MTc1MzQ0ODQ5NiwicGFzc3dvcmQiOiIkMmEkMTAkcWtDWm9tdTcweFpkYnlQV1NGN2tXZThDZktMT2RzdUxqNG9CQkVhc0NEaW5ST0tscXo0NHEiLCJzdWIiOiJhZG1pbkBnbWFpbC5jb20ifQ.XOVrWmMVSP8q79iIJuTH5iBSJaSKAXoTK93jKYx_ag8

{

}

###
//GET MES INTERVENTIONS
 GET http://localhost:8080/api/interventions/mesInterventions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImluZ2VuaWV1ckBnbWFpbC5jb20iLCJleHAiOjE3NTM4MTgyODEsInBhc3N3b3JkIjoiJDJhJDEwJHBER3RiLmM0a3ZzUDZOLzhyeC5DcWVDRkFkM29LcHR3YzNyZmwuQnJPVGdUbmJZLlN0ZEM2Iiwic3ViIjoiaW5nZW5pZXVyQGdtYWlsLmNvbSJ9.cUSF9G1nCPX_aH-1rfgQL75NB_PWGpoXnaI6GQjwsj0

{

}